version: '3.8'

services:
  migrations:
    build: .
    command: python manage.py makemigrations
    volumes:
      - .:/code

  base_migrations:
    build: .
    command: python manage.py makemigrations base
    volumes:
      - .:/code

  migrate:
    build: .
    command: python manage.py migrate
    volumes:
      - .:/code

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000