# Generated by Django 3.2.25 on 2024-04-22 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codechef',
            name='user_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='codeforces',
            name='user_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leetcode',
            name='user_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='codechef',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='codeforces',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='leetcode',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
