# Generated by Django 3.2.25 on 2024-04-21 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='topic',
        ),
        migrations.AddField(
            model_name='room',
            name='topic',
            field=models.ManyToManyField(blank=True, related_name='topics', to='base.Topic'),
        ),
    ]
