# Generated by Django 3.2.25 on 2024-04-04 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devtoken',
            name='token',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
