# Generated by Django 3.2.25 on 2024-04-23 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20240422_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingchange',
            name='contest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.contest'),
        ),
    ]
