# Generated by Django 3.2.25 on 2024-04-10 06:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_devtoken_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='submitted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problems', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='global_rank',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='number_of_codechef_contests',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='number_of_codeforces_contests',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='number_of_leetcode_contests',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='codechef_rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='codeforces_rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='leetcode_rating',
            field=models.IntegerField(null=True),
        ),
    ]
