# Generated by Django 3.2.25 on 2024-04-10 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20240410_0647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='global_rank',
            new_name='global_rank_codechef',
        ),
        migrations.AddField(
            model_name='user',
            name='global_rank_codeforces',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='global_rank_leetcode',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='number_of_codechef_questions',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='number_of_codeforces_questions',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='number_of_leetcode_questions',
            field=models.IntegerField(null=True),
        ),
    ]
