# Generated by Django 3.2.25 on 2024-04-10 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20240410_0912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='submitted_by',
        ),
        migrations.AddField(
            model_name='submission',
            name='submitted_by',
            field=models.OneToOneField(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL),
        ),
    ]
