# Generated by Django 3.2.25 on 2024-04-10 09:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20240410_0919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='submitted_by',
        ),
        migrations.AddField(
            model_name='submission',
            name='submitted_by',
            field=models.ManyToManyField(blank=True, related_name='submissions', to=settings.AUTH_USER_MODEL),
        ),
    ]
