# Generated by Django 3.2.25 on 2024-04-10 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20240410_0923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='submitted_by',
        ),
    ]
