# Generated by Django 3.2.25 on 2024-04-10 09:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_submission_submitted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devtoken',
            name='token',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='submitted_by',
            field=models.ManyToManyField(blank=True, related_name='problemstouser', to=settings.AUTH_USER_MODEL),
        ),
    ]
