# Generated by Django 3.2.25 on 2024-04-15 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20240410_0941'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('title', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('platform', models.CharField(choices=[('Codechef', 'Codechef'), ('Leetcode', 'Leetcode'), ('Codeforces', 'Codeforces')], max_length=10)),
                ('start_time', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('total_questions', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_edited_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='devtoken',
            name='token',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_change', models.IntegerField()),
                ('final_rating', models.IntegerField()),
                ('time_taken', models.DurationField()),
                ('rank', models.IntegerField()),
                ('number_of_problems_solved', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_edited_at', models.DateTimeField(auto_now=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratingchanges', to='base.contest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratingchanges', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
