# Generated by Django 3.2.25 on 2024-04-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20240415_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='time_taken',
            field=models.DurationField(null=True),
        ),
    ]
