# Generated by Django 3.2.25 on 2024-04-16 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_performance_time_taken'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_change', models.IntegerField()),
                ('final_rating', models.IntegerField()),
                ('time_taken', models.DurationField(null=True)),
                ('rank', models.IntegerField()),
                ('number_of_problems_solved', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_edited_at', models.DateTimeField(auto_now=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.contest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Performance',
        ),
    ]
