# Generated by Django 3.2.25 on 2024-04-17 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_auto_20240416_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='submitted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='contest',
            name='total_questions',
            field=models.IntegerField(null=True),
        ),
    ]
